name: Notify on OFAC changes

on:
  workflow_dispatch:
  push:
    branches:
      - ofac-notify
    # paths:
    #   - 'src/constants/sanctioned_addresses_ofac.json'
    paths:
      - 'test.txt'

jobs:
  send_slack_message:
    runs-on: pfl-main-ubuntu
    steps:
      - name: Send message to Slack
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_NOTIFICATION_CHANNEL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text":"GitHub Actions !"
          }' $SLACK_WEBHOOK